name: "Terraform"

on:
  push:
    branches:
      - master
    paths:
    - 'terraform/**'
    - '.github/workflows/terraform.yaml'
  pull_request:

env:
  working-directory: terraform
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Check if Terraform is Formatted Correctly
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Correcting Terraform Format for you.
        if: steps.fmt.outcome == 'failure'
        run: terraform fmt
      
      # https://github.com/marketplace/actions/add-commit
      - name: Add and Commit Format Fixes
        if: steps.fmt.outcome == 'failure'
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: "[skip ci]: Github Actions fix Terraform Formating"

      - name: Make safe env id
        id: env
        run: |
          string="${${{ github.repository}}.${{ github.ref_name }}//-\//.}"
          echo $string
          echo "env=$string" >> $GITHUB_OUTPUT

      # https://github.com/marketplace/actions/write-file
      # https://developer.hashicorp.com/terraform/language/settings/backends/configuration
      - name: Pass Backend
        uses: DamianReeves/write-file-action@master
        with:
          path: ${{ github.workspace }}/${{ env.working-directory }}/azure.tfbackend
          write-mode: overwrite
          contents: |
            resource_group_name  = "tfstate"
            storage_account_name = "${{ vars.AZ_TFSTATE_SA }}"
            container_name       = "tfstate"
            key                  = "${{ steps.env.outputs.env }}.tfstate"

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=azure.tfbackend

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # https://github.com/marketplace/actions/write-file
      - name: Pass Varibales
        uses: DamianReeves/write-file-action@master
        with:
          path: ${{ github.workspace }}/${{ env.working-directory }}/cicd.auto.tfvars
          write-mode: overwrite
          contents: |
            org = "${{ github.actor }}"
            github_repository = "${{ github.repository	}}"
            environment = "${{ github.ref_name }}"
            location = "${{ vars.AZ_REGION }}"
      
      - name: Check Files
        run: ls -lsa

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style üñå\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ‚öôÔ∏è\`${{ steps.init.outcome }}\`
            #### Terraform Validation ü§ñ\`${{ steps.validate.outcome }}\`
            #### Terraform Plan üìñ\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      # https://github.com/marketplace/actions/github-tag-bump
      - name: Bump version and push tag
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: anothrNick/github-tag-action@1.61.0 # Don't use @master unless you're happy to test the latest version
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
